### ISSUE TITLE
Ansible 2.5 isn't supported.

### ISSUE THREAD

**Issue by meierw** [karlmdavis/ansible-jenkins2#58]
The roles `jenkins_plugin` implementation doesn't work correctly while using Ansible 2.5
```
failed: [10.0.0.201] (item=cloudbees-folder) => {"changed": false, "item": "cloudbees-folder", "msg": "The params option to jenkins_plugin was removed in Ansible 2.5 since it circumvents Ansible's option handling"}
```
Fixed the problem locally by modifying the Install Plugins and Update Plugins tasks. Removed the params implementation like so:
```yaml
- name: Install Plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: present
    jenkins_home: "{{ jenkins_home }}"
    url: "{{ jenkins_url_local }}"
    url_username: "{{ jenkins_dynamic_admin_username | default(omit) }}"
    url_password: "{{ jenkins_dynamic_admin_password | default(omit) }}"
    validate_certs: "{{ false if ansible_distribution_release == 'trusty' else true }}"
    timeout: "{{ jenkins_plugins_timeout }}"
  with_items:
    - "{{ jenkins_plugins_recommended }}"
    - "{{ jenkins_plugins_extra }}"
  become: true
  notify:
    - "Restart Service 'jenkins'"
```

Haven't made a merge request, since now I'm pretty sure this change will break Ansible 2.4 usage.

Thoughts, suggestions? Perhaps you @karlmdavis are willing to drop 2.4 support?
